name: Build and Deploy to GitHub Pages

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip install Sphinx

      - name: Build documentation
        run: |
          cd docs/sources
          make html

      - name: Clone gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
        run: |
          git clone --quiet --branch=gh-pages https://github.com/AnsahMohammad/badge-magic-android gh-pages
          cd gh-pages
          rm -rf *
          cd ../
          cp -r ./docs/sources/_build/html/* ./gh-pages
          cd gh-pages
          git checkout --orphan temporary
          git branch -D gh-pages
          git branch -m gh-pages
          git add --all .
          git commit -am "[Auto] Update GH-Pages from $GITHUB_REF ($(date +%Y-%m-%d.%H:%M:%S))"
          git push origin gh-pages --force --quiet
